Import('env')
import SENFSCons

import glob
import os.path

###########################################################################

#for f in glob.glob('*.cc'):
#    bin = os.path.splitext(f)[0]
#    
#    SENFSCons.Binary(env, bin, f,
#                 LIBS = [ 'Scheduler', 'Packets', 'Socket', 'Utils' ],
#                 OBJECTS = [ '#/Packets/DefaultBundle/DefaultBundle.o',
#                             '#/Packets/MPEGDVBBundle/MPEGDVBBundle.o' ]);
