# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

SConscript(env.Glob("*/SConscript"))

SENFSCons.AutoPacketBundle(env, '80211Bundle', subdirs=['radiotap'])
