Import('env')
import SENFSCons

###########################################################################

SENFSCons.Binary(env, 'sniffer', SENFSCons.GlobSources(),
                LIBS = [ 'Scheduler', 'Packets', 'Socket', 'Utils' ]);
