# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

SConscript(glob.glob("*/SConscript"))

SENFSCons.AllIncludesHH(env, [ f for f in glob.glob("*.hh")
                               if f not in ('all_includes.hh','DVB.hh') and not f.endswith('.test.hh') ])

sources, includes = SENFSCons.Glob(env)

SENFSCons.Lib(env, sources)
SENFSCons.InstallIncludeFiles(env, includes)
