# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

SENFSCons.StandardTargets(env)

SENFSCons.AllIncludesHH(env, [ f for f in glob.glob("*.hh")
                               if f not in ('all_includes.hh','INet.hh') and not f.endswith('.test.hh') ])
sources = SENFSCons.GlobSources()
objects = SENFSCons.Objects( env, sources = sources )

SENFSCons.Doxygen(env)

Return('objects')
