# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

SENFSCons.AllIncludesHH(env, [ f for f in glob.glob("*.hh")
                               if ( f not in ('all_includes.hh','Logger.hh','SenfLog.hh')
                                    and not f.endswith('.test.hh') ) ])

sources, includes = SENFSCons.Glob(env)

SENFSCons.Lib(env, sources)
SENFSCons.Doxygen(env)

env.InstallSubdir(target = '$INCLUDEINSTALLDIR', source = includes)
