Import('env')
import SENFSCons

###########################################################################

SENFSCons.Binary(env, 'uledec', 'ULEdec.cc',
                 LIBS = [ 'Scheduler', 'Packets', 'Socket', 'Utils' ],
                 OBJECTS = [ '#/Packets/MPEGDVBBundle/MPEGDVBBundle.o' ]);

SENFSCons.Binary(env, 'mpedec', 'MPEdec.cc',
                 LIBS = [ 'Scheduler', 'Packets', 'Socket', 'Utils' ],
                 OBJECTS = [ '#/Packets/MPEGDVBBundle/MPEGDVBBundle.o' ]);
