#
# Copyright (c) 2020 Fraunhofer Institute for Applied Information Technology (FIT)
#                    Network Research Group (NET)
#                    Schloss Birlinghoven, 53754 Sankt Augustin, GERMANY
#                    Contact: support@wiback.org
#
# This file is part of the SENF code tree.
# It is licensed under the 3-clause BSD License (aka New BSD License).
# See LICENSE.txt in the top level directory for details or visit
# https://opensource.org/licenses/BSD-3-Clause
#


Import('env')
import SENFSCons, glob, os.path, yaptu

###########################################################################

sconscripts = sorted(list(set(env.Glob("*/SConscript", strings=True))))

if sconscripts:
    SENFSCons.IndexPage(env, 'Mainpage.dox', title="Extensions",
                        text="""This folder contains additional SENF extensions which are built
                                into the senf library but are not part of senf proper.""")

    SConscript(sconscripts)

    env.Clean('all','Mainpage.dox')
    env.Clean('all_docs','Mainpage.dox')

    SENFSCons.Doxygen(env)
