# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

SENFSCons.AllIncludesHH(env, exclude=['Socket.hh'])
SENFSCons.AutoRules(env, doc_extra_sources = [
    env.Dia2Png('SocketLibrary-classes.dia'),
    env.Dia2Png('FhHierarchy.dia'),
    env.Dia2Png('SocketPolicy.dia'),
    env.Dia2Png('Protocols.dia'),
    env.Dia2Png('Handle.dia'),
])
