Import('env')
import SENFSCons, glob

###########################################################################

#sources = SENFSCons.GlobSources()

#SENFSCons.StandardTargets(env)

#SENFSCons.Object(env, 
#    target = 'psi2ts.o', 
#    sources = sources,
#    LIBS = ['senf'])
