# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

import yaptu

HOWTOS = []
for dox in sorted(glob.glob("*/Mainpage.dox")):
    title = ([None] + [ line.split('\\mainpage',1)[-1].strip() for line in file(dox)
                        if '\\mainpage' in line ])[-1]
    if title:
        HOWTOS.append( (dox.split('/',1)[0], title) )

MAINPAGE="""
/** \mainpage HowTo's

    \htmlonly
    <dl>

{{  for name, title in HOWTOS:
      <dt><a href="../../${name}/doc/html/index.html">${name}</a></dt><dd>${title}</a></dd>
}}

    </dl>
    \endhtmlonly
 */
"""

file("Mainpage.dox","w").write(yaptu.process(MAINPAGE, globals(), env.Dictionary()))

SConscript(glob.glob("*/SConscript"))

SENFSCons.Doxygen(env)
