# -*- python -*-

Import('env')
import SENFSCons, glob, os.path

###########################################################################

sources, tests, includes = SENFSCons.Glob(env, subdirs=[ 'impl' ])

env.Append(ALLOBJECTS = env.Object(sources))
env.BoostUnitTest('test', tests)
SENFSCons.Doxygen(env)
env.InstallSubdir('$INCLUDEINSTALLDIR', includes)

SConscript(glob.glob("*/SConscript"))
