# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

SENFSCons.AutoRules(env, subdirs=['impl'])
SENFSCons.CopyToVariantDir(env, 'Daemon.hh')
