# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

SENFSCons.AllIncludesHH(env, exclude=['INet.hh'])
SENFSCons.AutoRules(env)
SENFSCons.CopyToVariantDir(env, 'INet.hh')
