# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

sources, includes = SENFSCons.Glob(env, exclude=[ 'telnetServer.cc'])

SENFSCons.Lib(env, sources)
SENFSCons.Doxygen(env)

env.InstallSubdir(target = '$INCLUDEINSTALLDIR', source = includes)

SENFSCons.Binary(env, "telnetServer", ['telnetServer.cc'])
