# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

sources, tests, includes = SENFSCons.Glob(env, exclude=[ 'telnetServer.cc'])

env.Append(ALLOBJECTS = env.Object(sources))
env.BoostUnitTest('test', tests)
SENFSCons.Doxygen(env)
env.InstallSubdir('$INCLUDEINSTALLDIR', includes)
env.Program('telnetSserver', ['telnetServer.cc'])
