# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

SENFSCons.AllIncludesHH(env, exclude=['Raw.hh'])
SENFSCons.AutoRules(env)
