# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

SENFSCons.AllIncludesHH(env, [ f for f in glob.glob("*.hh")
                               if f not in ('all_includes.hh','UN.hh') and not f.endswith('.test.hh') ])

sources = SENFSCons.GlobSources()

allob = []

allob.extend(
    SENFSCons.Objects( env, sources = sources, LIBS = [ 'Socket', 'Scheduler', 'Utils' ] ) )

for sc in glob.glob("*/SConscript"):
    ob = SConscript(sc)
    if ob : allob.extend(ob)

SENFSCons.InstallIncludeFiles(env, [ 'UN.hh', 'all_includes.hh' ])

Return('allob')
