Import('env')
import SENFSCons

###########################################################################

SENFSCons.Binary(env, 'client', 'client.cc',
                LIBS = [ 'Packets', 'Socket', 'Scheduler', 'Utils' ]);

SENFSCons.Binary(env, 'server', 'server.cc',
                LIBS = [ 'Scheduler', 'Packets', 'Socket', 'Scheduler', 'Utils' ]);
