Import('env')
import SENFSCons

###########################################################################

env.Alias('examples', env.Program('client', 'client.cc'))
env.Alias('examples', env.Program('server', 'server.cc'))
