Import('env')
import SENFSCons

###########################################################################

SENFSCons.Binary(env, 'client', 'client.cc');
SENFSCons.Binary(env, 'server', 'server.cc');
