Import('env')
import SENFSCons

###########################################################################

env.Program('udpClient', 'udpClient.cc')
env.Program('udpServer', 'udpServer.cc')

SENFSCons.Doxygen(env)
