Import('env')
import SENFSCons

###########################################################################

env.Default(env.Program('udpClient', 'udpClient.cc'))
env.Default(env.Program('udpServer', 'udpServer.cc'))

SENFSCons.Doxygen(env)
