Import('env')
import SENFSCons

###########################################################################

SENFSCons.Binary(env, 'udpClient', 'udpClient.cc');
SENFSCons.Binary(env, 'udpServer', 'udpServer.cc',);
SENFSCons.Doxygen(env)
