# -*- python -*-

import sys
sys.path.extend(['senf/site_scons', '../../site_scons'])
import senfutil

env = Environment()
senfutil.SetupForSENF(env)
senfutil.DefaultOptions(env)

env.Default( env.Program('udpClient', ['udpClient.cc']) )
env.Default( env.Program('udpServer', ['udpServer.cc']) )
