# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

sources, includes = SENFSCons.Glob(env)

SENFSCons.Lib(env, sources)
SENFSCons.Doxygen(env)
SENFSCons.InstallIncludeFiles(env, includes)
