# -*- python -*-

Import('env')
import SatSCons

###########################################################################

sources = SatSCons.GlobSources()
SatSCons.StandardTargets(env)
SatSCons.Lib(env,
             library = 'Scheduler',
             sources = sources,
             LIBS = [ 'Socket', 'Utils' ])
SatSCons.Doxygen(env)
