Import('env')
import SatSCons

###########################################################################

SatSCons.StandardLib(env,
                     library = 'Scheduler',
                     sources = SatSCons.GlobSources(),
                     LIBS = [ '$LIB_Utils' ])
