# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

sources, tests, includes = SENFSCons.Glob(env)

objects = env.Object(sources)
cobject = env.CombinedObject('DefaultBundle', objects)
env.Default(cobject)
env.Append(ALLOBJECTS = objects)
env.Append(PACKET_BUNDLES = cobject)
env.BoostUnitTest('test', tests + cobject)

env.Install('$OBJINSTALLDIR', cobject)
env.InstallSubdir('$INCLUDEINSTALLDIR', includes)

SConscript(glob.glob("*/SConscript"))
