# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

SENFSCons.AutoPacketBundle(env, 'DefaultBundle')
SENFSCons.CopyToVariantDir(env, 'EUI64Parser.hh')