# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

sources, tests, includes = SENFSCons.Glob(env)

env.BoostUnitTest('test', tests + ['${ALLBUNDLES}'])
