Import('env')
import SENFSCons, glob

###########################################################################

SConscript(glob.glob("*/SConscript"))

SENFSCons.AllIncludesHH(env, [ f for f in glob.glob("*.hh")
                               if f not in ('all_includes.hh','PPI.hh') \
                                  and not f.endswith('.test.hh') ])

sources, includes = SENFSCons.Glob(env, subdirs=[ 'detail' ])

SENFSCons.Lib(env, sources)
SENFSCons.Doxygen(env, extra_sources=[
    env.Dia2Png('scenario.dia'),
    env.Dia2Png('classes.dia'),
    env.Dia2Png('ratestuffer.dia'),
])
SENFSCons.InstallIncludeFiles(env, includes)
