# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

SConscript(glob.glob("*/SConscript"))

sources, includes = SENFSCons.Glob(env)
SENFSCons.Lib(env, sources)

env.InstallSubdir(target = '$INCLUDEINSTALLDIR', source = includes)
