# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

(sources, tests), includes = SENFSCons.Glob(env)

SENFSCons.Object(env, target='80211Bundle', sources=sources,
                 testSources = tests + [ '80211Bundle.o' ])
SENFSCons.Lib(env, sources=sources)

env.InstallSubdir(target = '$INCLUDEINSTALLDIR', source = includes)

SConscript(glob.glob("*/SConscript"))
