# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

sources, includes = SENFSCons.Glob(env)

SENFSCons.Object(env, target='80211Bundle', sources=sources)
SENFSCons.Lib(env, sources=sources[0])
SENFSCons.InstallIncludeFiles(env, includes)

SConscript(glob.glob("*/SConscript"))
