# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

SENFSCons.AllIncludesHH(env, exclude=['Logger.hh','SenfLog.hh'])

sources, tests, includes = SENFSCons.Glob(env)

env.Append(ALLOBJECTS = env.Object(sources))
env.BoostUnitTest('test', tests)
SENFSCons.Doxygen(env)
env.InstallSubdir('$INCLUDEINSTALLDIR', includes)
