Import('env')
import SENFSCons

###########################################################################

SENFSCons.Binary(env, 'sniffer', SENFSCons.GlobSources(),
                 LIBS = [ 'Scheduler', 'Packets', 'Socket', 'Utils' ],
                 OBJECTS = [ '#/Packets/DefaultBundle/DefaultBundle.o' ]);
