# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

sources, tests, includes = SENFSCons.Glob(env)

env.Alias('examples', env.Program('sniffer', sources + [ '${LOCALLIBDIR}/AllBundles.o' ]))
SENFSCons.Doxygen(env)
