#
# Copyright (c) 2020 Fraunhofer Institute for Applied Information Technology (FIT)
#                    Network Research Group (NET)
#                    Schloss Birlinghoven, 53754 Sankt Augustin, GERMANY
#                    Contact: support@wiback.org
#
# This file is part of the SENF code tree.
# It is licensed under the 3-clause BSD License (aka New BSD License).
# See LICENSE.txt in the top level directory for details or visit
# https://opensource.org/licenses/BSD-3-Clause
#


import os
import os.path
import sys
try: sys.path.append(((_ for _ in (os.path.join(os.path.sep.join(('..' for _ in range(_))),d,
     'site_scons') for d in ('../../../../','senf','Senf') for _ in range(len(os.getcwd().split('/'))))
     if os.path.exists(_))).next())
except: pass
import senfutil

env = Environment()
senfutil.SetupForSENF(env, exit_if_not_found=True)
senfutil.NetEmu.SetupForNetEmu(env)
senfutil.DefaultOptions(env)

sources = senfutil.Glob(env, exclude = ['80211Analyzer.cc', 'wlanMon2Eth.cc'])[0]

### the boost libs should be linked staticly:
boostlibs = [ '-l%s' % lib for lib in env['LIBS'] if lib.startswith('$BOOST') ]
env.Replace( LIBS      = [ lib for lib in env['LIBS'] if not lib.startswith('$BOOST') ] )
env.Append(  LINKFLAGS = [ '-Wl,-Bdynamic' ],
             LINKCOM   = ' -Wl,-Bstatic ' + ' '.join(boostlibs) + ' -Wl,-Bdynamic' )

env.Default( env.Program('80211Analyzer', sources + ['80211Analyzer.cc', '${BUNDLEDIR}/AllBundles${LIBADDSUFFIX}.o']) )

env.Program('wlanMon2Eth', ['wlanMon2Eth.cc', '$BUNDLEDIR/AllBundles.o'])
