# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

SENFSCons.Test(env, sources = glob.glob("*.test.cc"),
               LIBS = [ 'Packets_DefaultBundle', 'Packets', 'Socket', 'Utils' ])
