# -*- python -*-

Import('env')
import SENFSCons, glob, os.path

###########################################################################

SENFSCons.StandardTargets(env)

# OUCH ... another hack to work around a scons bug ...
if not os.path.exists("Logger/all_includes.hh"):
    Execute(Touch("Logger/all_includes.hh"))

sources, testSources = SENFSCons.GlobSources()
objects = SENFSCons.Objects( env, sources = sources, testSources=testSources )

lib = SENFSCons.Lib(env,
                    library = 'Utils',
                    sources = objects)

SENFSCons.Doxygen(env)
SENFSCons.InstallIncludeFiles(env, [ 'Logger.hh', 'Daemon.hh' ])

SConscript(glob.glob("*/SConscript"))
