# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

SENFSCons.StandardTargets(env)

sources, testSources = SENFSCons.GlobSources()
objects = SENFSCons.Objects( env, sources = sources, testSources=testSources )

for sc in glob.glob("*/SConscript"):
    ob = SConscript(sc)
    if ob : objects.extend(ob)

SENFSCons.Lib(env,
              library = 'Utils',
              sources = objects)

SENFSCons.Doxygen(env)
SENFSCons.InstallIncludeFiles(env, [ 'Logger.hh', 'Daemon.hh' ])
