# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

sources, includes = SENFSCons.Glob(env)

SENFSCons.StandardTargets(env)
SENFSCons.Object(env, target='MPEGDVBBundle', sources=sources)
SENFSCons.Lib(env, sources[0])
SENFSCons.InstallIncludeFiles(env, includes)
