# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

(sources, tests), includes = SENFSCons.Glob(env)

SENFSCons.Object(env, target = '80221Bundle', sources=sources,
                 testSources = tests + [ '80221Bundle.o' ])
SENFSCons.Lib(env, sources)

SConscript(glob.glob("*/SConscript"))
