# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

sources, tests, includes = SENFSCons.Glob(env)

objects = env.Object(sources)
env.Install('$OBJINSTALLDIR', env.Default( env.CombinedObject('80221Bundle', objects) ))
env.Append(ALLOBJECTS = objects)
env.BoostUnitTest('test', tests + ['80221Bundle.o'])

env.InstallSubdir('$INCLUDEINSTALLDIR', includes)

SConscript(glob.glob("*/SConscript"))
