# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

sources, includes = SENFSCons.Glob(env)

SENFSCons.Object(env, target = '80221Bundle', sources=sources)
SENFSCons.Lib(env, sources[0])

SConscript(glob.glob("*/SConscript"))
