# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

(sources, tests), includes = SENFSCons.Glob(env)

SENFSCons.Object(env, target='DefaultBundle', sources=sources, 
                 testSources=tests + [ 'DefaultBundle.o' ])
SENFSCons.Lib(env, sources)

env.InstallSubdir(target = '$INCLUDEINSTALLDIR', source = includes)

SConscript(glob.glob("*/SConscript"))
