# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

sources, includes = SENFSCons.Glob(env)

SENFSCons.Object(env, target='DefaultBundle', sources=sources)
SENFSCons.Lib(env, sources[0])

env.InstallSubdir(target = '$INCLUDEINSTALLDIR', source = includes)

SConscript(glob.glob("*/SConscript"))
