# -*- python -*-

Import('env')
import SENFSCons
import glob

###########################################################################

sources, testSources = SENFSCons.GlobSources()

SENFSCons.StandardTargets(env)

subob = []
for sc in glob.glob("*/SConscript"):
    ob = SConscript(sc)
    if ob : subob.extend(ob)

SENFSCons.Lib(env,
              library = 'Socket',
              sources = sources + subob,
              testSources = testSources,
              LIBS = [ 'Utils' ])

SENFSCons.Doxygen(env, extra_sources = [
    env.Dia2Png('SocketLibrary-classes.dia'),
    env.Dia2Png('FhHierarchy.dia'),
    env.Dia2Png('SocketPolicy.dia'),
    env.Dia2Png('Protocols.dia'),
    env.Dia2Png('Handle.dia'),
])

