# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

sources = SENFSCons.GlobSources()

SENFSCons.StandardTargets(env)

SENFSCons.Lib(env,
             library = 'Socket',
             sources = sources,
             LIBS = [ 'Utils' ])

SENFSCons.Doxygen(env, extra_sources = [
    env.Dia2Png('SocketLibrary-classes.dia'),
    env.Dia2Png('FhHierarchy.dia'),
    env.Dia2Png('SocketPolicy.dia'),
    env.Dia2Png('Protocols.dia'),
    env.Dia2Png('Handle.dia'),
])
