# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

sources, includes = SENFSCons.Glob(env)

SENFSCons.StandardTargets(env)
SENFSCons.Lib(env, sources)
SENFSCons.Doxygen(env, extra_sources = [
    env.Dia2Png("structure.dia"),
    env.Dia2Png("MPEGDVBBundle/TLV.dia")
])
SENFSCons.InstallIncludeFiles(env, includes)

SConscript(glob.glob("*/SConscript"))

