Import('env')
import SatSCons

###########################################################################

sources = SatSCons.GlobSources()
SatSCons.StandardTargets(env)
SatSCons.Lib(env, 'Packets',  sources)
env.AddPreAction(
    SatSCons.Doxygen(env,sources),
    env.Action("make -f imgconvert.mak structure.png"))
    
