#
# Copyright (c) 2020 Fraunhofer Institute for Applied Information Technology (FIT)
#                    Network Research Group (NET)
#                    Schloss Birlinghoven, 53754 Sankt Augustin, GERMANY
#                    Contact: support@wiback.org
#
# This file is part of the SENF code tree.
# It is licensed under the 3-clause BSD License (aka New BSD License).
# See LICENSE.txt in the top level directory for details or visit
# https://opensource.org/licenses/BSD-3-Clause
#


import os
import sys
try: sys.path.append(((_ for _ in (os.path.join(os.path.sep.join(('..' for _ in range(_))),d,
     'site_scons') for d in ('senf','Senf') for _ in range(len(os.getcwd().split('/'))))
     if os.path.exists(_))).next())
except: pass
import senfutil

env = Environment()
senfutil.SetupForSENF(env, exit_if_not_found=True)
senfutil.NetEmu.SetupForNetEmu(env)
senfutil.DefaultOptions(env)
env.Append(CXXFLAGS = ['-Wno-missing-field-initializers', '-g'],
           LINKFLAGS = ['-g'])
env.Replace(LINKFLAGS_normal = [])

env.Default(env.Program('fwNetEmu', ['main.cc']))
