# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

sources, includes = SENFSCons.Glob(env)

SENFSCons.Lib(env, sources)
SENFSCons.Doxygen(env)

env.InstallSubdir(target = '$INCLUDEINSTALLDIR', source = includes)
