# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

SENFSCons.StandardTargets(env)

sources = SENFSCons.GlobSources()

SENFSCons.Lib( env,
               library = 'Utils_Daemon',
               sources = sources,
               LIBS = [ 'Scheduler', 'Socket', 'Utils' ] )

SENFSCons.Doxygen(env)
