# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

sources, tests, includes = SENFSCons.Glob(env, exclude=['testServer.cc'])

env.Append(ALLOBJECTS = env.Object(sources))
env.BoostUnitTest('test', tests)
SENFSCons.Doxygen(env)
env.InstallSubdir('$INCLUDEINSTALLDIR', includes)
env.Program('testServer', ['testServer.cc'])
