# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

SENFSCons.AllIncludesHH(env, exclude=['DVB.hh'])
SENFSCons.AutoRules(env)
SENFSCons.CopyToVariantDir(env, 'DVB.hh')