# -*- python -*-

Import('env')
import SENFSCons

env.SetDefault(
    RADIOTAP_URL = 'http://git.sipsolutions.net/radiotap.git',
    )

env.PhonyTarget(
    'update-radiotap', [],
    [ Delete('$GITDIR'),
      'git clone $RADIOTAP_URL $GITDIR',
      'cp $RADIOTAP_FILES $HERE',
      Delete('$GITDIR') ],
    HERE           = env.Dir('.'),
    GITDIR         = env.Dir('radiotap.git'),
    RADIOTAP_FILES = [ env.Dir('radiotap.git').File(f)
                       for f in env.Glob("*.h") + env.Glob("*.c") ])
