#
# Copyright (c) 2020 Fraunhofer Institute for Applied Information Technology (FIT)
#                    Network Research Group (NET)
#                    Schloss Birlinghoven, 53754 Sankt Augustin, GERMANY
#                    Contact: http://wiback.org
#
# This file is part of the SENF code tree.
# It is licensed under the 3-clause BSD License (aka New BSD License).
# See LICENSE.txt in the top level directory for details or visit
# https://opensource.org/licenses/BSD-3-Clause
#


Import('env')
import SENFSCons

env.SetDefault(
    RADIOTAP_URL = 'http://git.sipsolutions.net/radiotap.git',
    )

env.PhonyTarget(
    'update-radiotap', [],
    [ Delete('$GITDIR'),
      'git clone $RADIOTAP_URL $GITDIR',
      'cp $RADIOTAP_FILES $HERE',
      Delete('$GITDIR') ],
    HERE           = env.Dir('.'),
    GITDIR         = env.Dir('radiotap.git'),
    RADIOTAP_FILES = [ env.Dir('radiotap.git').File(f)
                       for f in env.Glob("*.h") + env.Glob("*.c") ])
