#!/bin/sh

base="`dirname "$0"`"; base="`cd "$base"; pwd`"

sconsbase="$(ls -d "$base/scons-"* | sort | tail -1)"
sconsengine="$sconsbase/engine"
sconsscript="$sconsbase/script/scons"

export SCONS_LIB_DIR="$sconsengine"
exec "$sconsscript" "$@"
