#
# Copyright (c) 2020 Fraunhofer Institute for Applied Information Technology (FIT)
#                    Network Research Group (NET)
#                    Schloss Birlinghoven, 53754 Sankt Augustin, GERMANY
#                    Contact: support@wiback.org
#
# This file is part of the SENF code tree.
# It is licensed under the 3-clause BSD License (aka New BSD License).
# See LICENSE.txt in the top level directory for details or visit
# https://opensource.org/licenses/BSD-3-Clause
#


Import('env')
import SENFSCons, os, re

###########################################################################

env.Default(env.Local('PPI.hh'), env.Local('Socket.hh'), env.Local('Packets.hh'))

# Create local_config.h
if not env.GetOption('clean') and not os.path.exists("local_config.hh"):
    Execute(Copy("local_config.hh", os.path.join(env.Dir('#').abspath, 'senf', 'local_config_sample.hh')))

# Ext/SConscript is last so it can depend on env vars set by any other script
# (e.g. $PACKET_BUNDLES)
SConscript(sorted(list(set(env.Glob("*/SConscript", strings=True)) - set(("Ext/SConscript",)))))
SConscript("Ext/SConscript")

env.InstallSubdir(target = '$INCLUDEINSTALLDIR', 
                  source = sorted(env.Glob("*.hh", strings=True)))

# Create Version.hh
env.CreateVersionFile( "Version.hh", name='SENF', major_version=1, minor_version=2,
                       local_revision_file='.revision',
                       directory = env.Dir('#').abspath)

