#
# Copyright (c) 2020 Fraunhofer Institute for Applied Information Technology (FIT)
#                    Network Research Group (NET)
#                    Schloss Birlinghoven, 53754 Sankt Augustin, GERMANY
#                    Contact: http://wiback.org
#
# This file is part of the SENF code tree.
# It is licensed under the 3-clause BSD License (aka New BSD License).
# See LICENSE.txt in the top level directory for details or visit
# https://opensource.org/licenses/BSD-3-Clause
#


Import('env')
import SENFSCons

###########################################################################

SENFSCons.AllIncludesHH(env, exclude = ['PPI.hh'])
SENFSCons.AutoRules(env, subdirs=['detail'], doc_extra_sources=[
        env.Dia2Png('scenario.dia'),
        env.Dia2Png('classes.dia'),
        env.Dia2Png('ratestuffer.dia'),
])
