# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

SENFSCons.AllIncludesHH(env, exclude = ['PPI.hh'])
SENFSCons.AutoRules(env, subdirs=['detail'], doc_extra_sources=[
        env.Dia2Png('scenario.dia'),
        env.Dia2Png('classes.dia'),
        env.Dia2Png('ratestuffer.dia'),
])
