# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

sources, tests, includes = SENFSCons.Glob(env)

env.Default(env.Program('mcsniffer', sources + env['PACKET_BUNDLES']))
