# -*- python -*-

Import('env')
import SENFSCons

###########################################################################

sources, tests, includes = SENFSCons.Glob(env)

env.Program('mcsniffer', sources + [ '${LOCALLIBDIR}/AllBundles.o' ])
