# -*- python -*-

Import('env')
import SENFSCons, glob

###########################################################################

sources = SENFSCons.GlobSources()

SENFSCons.StandardTargets(env)

SENFSCons.Object(env, target = 'RTPBundle', sources=sources,
                 LIBS = ['Packets', 'Socket', 'Utils'],
                 OBJECTS = ['#/Packets/DefaultBundle/DefaultBundle.o'])
                 
