#
# Copyright (c) 2020 Fraunhofer Institute for Applied Information Technology (FIT)
#                    Network Research Group (NET)
#                    Schloss Birlinghoven, 53754 Sankt Augustin, GERMANY
#                    Contact: http://wiback.org
#
# This file is part of the SENF code tree.
# It is licensed under the 3-clause BSD License (aka New BSD License).
# See LICENSE.txt in the top level directory for details or visit
# https://opensource.org/licenses/BSD-3-Clause
#


import sys, os, os.path
try: sys.path.append(((_ for _ in (os.path.join(os.path.sep.join(('..' for _ in range(_))),d,
     'site_scons') for d in ('senf','Senf') for _ in range(len(os.getcwd().split('/'))))
     if os.path.exists(_))).next())
except: pass
import os.path, glob, senfutil

env = Environment(ENV = os.environ)
senfutil.parseArguments(env)
senfutil.SetupForSENF(env)
senfutil.NetEmu.SetupForNetEmu(env)
senfutil.DefaultOptions(env)

rev = 'r' + os.popen("svnversion").read().strip().lower()
if rev == 'rexported':
    rev = os.popen("gitsvnversion").read().strip().lower()

env.Replace(
    LOGLEVELS_normal = [ 'senf::log::Debug||VERBOSE' ],
    LOGLEVELS_debug  = [ '$LOGLEVELS_normal' ],

    PROJECTNAME      = 'CARMEN dummy router',
    COPYRIGHT        = "2009 Fraunhofer FOKUS.NetBi",
    DOCLINKS         = [ ('NetForge', 'https://netforge.fokus.fraunhofer.de/projects/show/netemu') ],
    REVISION         = rev,
)

sources, tests = senfutil.Glob(env, exclude=[ 'main.cc' ])
objects        = env.Object(sources)

carmen         = env.Program('carmen', objects + [ 'main.cc' ], LIBS = ['$LIBS'])
if tests       : env.BoostUnitTest('test', objects + tests)

env.Default(carmen)

senfutil.Doxygen(env)

env.Alias('all', [ 'test', carmen, 'doc' ])


# Local Variables:
# mode: python
# fill-column: 100
# indent-tabs-mode: nil
# ispell-local-dictionary: "american"
# End:
